name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@3.29.245.214:/home/ubuntu/devops-html-project

      - name: Deploy Docker + Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.29.245.214 << 'EOF'
            set -e
            cd /home/ubuntu/devops-html-project

            # Install nginx if not installed
            if ! command -v nginx > /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y nginx
            fi

            # Stop old nginx service (avoid conflicts)
            sudo systemctl stop nginx || true

            # Enable nginx on boot
            sudo systemctl enable nginx

            # Stop and remove old Docker container
            sudo docker stop devops-app || true
            sudo docker rm devops-app || true

            # Build Docker image
            sudo docker build -t devops-html-project .

            # Run Docker on port 3000
            sudo docker run -d -p 3000:80 --name devops-app devops-html-project

            # Create Nginx reverse proxy config
            echo "server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
            }" | sudo tee /etc/nginx/sites-available/devops-html-project

            # Enable site and reload nginx
            sudo ln -sf /etc/nginx/sites-available/devops-html-project /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
          EOF
