name: Deploy to EC2

on:
  push:
    branches:
      - main   # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@3.29.245.214:/home/ubuntu/devops-html-project

      - name: Deploy with Docker and Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.29.245.214 << 'EOF'
            set -e
            cd /home/ubuntu/devops-html-project

            # Install nginx if not installed
            if ! command -v nginx > /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y nginx
            fi

            # Enable nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx || true

            # Copy nginx config from project root
            sudo cp nginx /etc/nginx/sites-available/devops-html-project

            # Remove existing symlink and create a new one
            sudo rm -f /etc/nginx/sites-enabled/devops-html-project
            sudo ln -s /etc/nginx/sites-available/devops-html-project /etc/nginx/sites-enabled/

            # Test and reload nginx
            sudo nginx -t
            sudo systemctl reload nginx

            # Build Docker image
            sudo docker build -t devops-html-project .

            # Stop and remove old container if exists
            sudo docker stop devops-app || true
            sudo docker rm devops-app || true

            # Run Docker container on port 8080 (internal)
            sudo docker run -d -p 8080:80 --name devops-app devops-html-project
          EOF
